apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: restapi-binding
  namespace: default
spec:
  params:
    - name: gitshortrev
      value: $(event.head_commit.id|@cut:6)
    - name: gitrevision
      value: $(event.head_commit.id)
    - name: gitrepositoryurl
      value: $(event.repository.url)
    - name: namespace
      value: default
