apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: restapi
  labels:
    app: restapi
spec:
  template:
    metadata:
      labels:
        app: restapi
    spec:
      initContainers:
      - name: setup-db
        image: arey/mysql-client:latest
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-restapi-instance
              key: endpoint
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-restapi-instance
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-restapi-instance
              key: password
        - name: MYSQL_DATABASE
          value: demo
        command:
          - mysql
          - -h
          - $(MYSQL_HOST)
          - -u
          - $(MYSQL_USER)
          - -p$(MYSQL_PASSWORD)
          - -e
          - CREATE DATABASE IF NOT EXISTS $(MYSQL_DATABASE);
      containers:
      - name: restapi
        image: 181151069204.dkr.ecr.eu-west-1.amazonaws.com/rj45:latest
        env:
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-restapi-instance
              key: endpoint
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-restapi-instance
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-restapi-instance
              key: password
        - name: MYSQL_DATABASE
          value: demo
        ports:
        - containerPort: 8080
          name: restapi
---
apiVersion: v1
kind: Service
metadata:
  name: restapi
  labels:
    app: restapi
spec:
  ports:
  - port: 80
  selector:
    app: restapi
  type: LoadBalancer
