---
# AWS Credentials secret - used by AWS Provider
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials: BASE64ENCODED_AWS_PROVIDER_CREDS
---
# AWS Provider with credential secret reference - used to provision aws resources
apiVersion: aws.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: aws-provider
  namespace: crossplane-system
spec:
  credentialsSecretRef:
    key: credentials
    name: aws-creds
  region: eu-west-1
